### ISSUE TITLE
Convert ISO-8859-1 to UTF-8.

### ISSUE THREAD

**Issue by GermanBluefox** [instalator/iobroker.mikrotik#1]
admin/Words.js

**Comment by instalator** [comment]
Я его не правил, это из темплейта файл

**Comment by GermanBluefox** [comment]
Всё равно поменяй :)

2017-07-24 12:35 GMT+02:00 Vladimir Vilisov <notifications@github.com>:

**Comment by instalator** [comment]
Готово.
