### ISSUE TITLE
Do not generate objectds/tates with ",", "?", "[" and "]" and ' and " and spaces in it!!

### ISSUE THREAD

**Issue by Apollon77** [instalator/ioBroker.mikrotik#10]
see https://github.com/ioBroker/ioBroker.js-controller/issues/198

According to https://forum.iobroker.net/viewtopic.php?f=36&t=13700&p=145069#p150508 minimum with one user your states contained a * as character. Please make sure this is replaced and not used as character for a state-id/object id

Thank you very much!

**Comment by Apollon77** [comment]
Added spaces as forbidden character too

**Comment by instalator** [comment]
Please check https://github.com/instalator/ioBroker.mikrotik/commit/c4f8d01d119c4ff2ff032963f950bf88f38184eb

**Comment by Apollon77** [comment]
Can only * happen? Why not replace the full list?
In the linked js-controller is a full Regex available

**Comment by instalator** [comment]
Only * could be.

**Comment by Apollon77** [comment]
Then fine ;-)
