### ISSUE TITLE
Update stable version in repo to 1.0.10

### ISSUE THREAD

**Issue by GermanBluefox** [instalator/ioBroker.mikrotik#29]
# Think about update stable version to 1.0.10
**Version**: stable=**1.0.4** (524 days old) => latest=**1.0.10** (39 days old)
**Installs**: stable=**148** (63.52%), latest=**62** (26.61%), total=**233**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L781)

**Comment by instalator** [comment]
https://github.com/ioBroker/ioBroker.repositories/pull/663
