### ISSUE TITLE
Update stable version in repo from 1.0.11 to 1.0.12

### ISSUE THREAD

**Issue by GermanBluefox** [instalator/ioBroker.mikrotik#30]
# Think about update stable version to 1.0.12
**Version**: stable=**1.0.11** (64 days old) => latest=**1.0.12** (15 days old)
**Installs**: stable=**100** (41.49%), latest=**49** (20.33%), total=**241**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L847)

**Comment by instalator** [comment]
not valid
