### ISSUE TITLE
CAPsMAN integration

### ISSUE THREAD

**Issue by cocoon77** [instalator/ioBroker.mikrotik#33]
Hey, it would be great if you could integrate CAPsMAN with the registration-table.
So it would be possible to check the availability of a wifi device.

Thanks so much for all your work you have done!

**Comment by instalator** [comment]
Give me the API command with the required data.

**Comment by cocoon77** [comment]
The command in the terminal is `/caps-man registration-table pr` this shows you all connected devices.
Please collect Interface, SSID, MAC-Adress, Uptime and RX-Signal

[Manual:CAPsMAN](https://wiki.mikrotik.com/wiki/Manual:CAPsMAN)

**Comment by instalator** [comment]
I don't use CapsMan and have no way to check.
Execute `caps-man/registration-table/print` in `mikrotik.0.commands.raw` and give me the result from the object `mikrotik.0.commands.response`.

**Comment by cocoon77** [comment]
`mikrotik.0.commands.response`:

`[{".id":"*1","interface":"2.4GHz--MikroTik","ssid":"XX","mac-address":"XX:XX:XX:XX:XX:XX","tx-rate":"72.2Mbps-20MHz/1S/SGI","rx-rate":"54Mbps","rx-signal":"-67","uptime":"6h26m53s390ms","packets":"164373,129681","bytes":"11980887,26210517","tx-rate-set":"OFDM:6-54 BW:1x SGI:1x HT:0-7","eap-identity":"","comment":"Device-01"},{".id":"*2","interface":"2.4GHz--MikroTik","ssid":"XX","mac-address":"XX:XX:XX:XX:XX:XX","tx-rate":"65Mbps-20MHz/1S/SGI","rx-rate":"18Mbps","rx-signal":"-64","uptime":"6h26m53s250ms","packets":"198880,155137","bytes":"15095260,37271664","tx-rate-set":"OFDM:6-54 BW:1x SGI:1x HT:0-7","eap-identity":"","comment":"Device-02"}]`
...

**Comment by instalator** [comment]
Update from github and check

**Comment by cocoon77** [comment]
Looks good except one issue.
If a device disconnect and reconnect again it gets a new ID and the old entry still exist.

Here an example of multiple entries of the same device:
![Example](https://user-images.githubusercontent.com/70833614/107877185-239f7000-6ecb-11eb-8795-d63499a5967e.png)

**Comment by instalator** [comment]
I replaced id with a mac address. Update from github and check

**Comment by cocoon77** [comment]
No duplicate entries anymore well done!
The only "issue" left is like on most other entries, they dont get erased if they dont exist anymore but thats fine for me.
thx!
