### ISSUE TITLE
RAW API Commands problem

### ISSUE THREAD

**Issue by andromedi4** [instalator/ioBroker.mikrotik#34]
Hello,
I`ve problem with api commands.
Command  /ip/kid-control/pause work, but pause for all kids.

Command  /ip/kid-control/pause=kid1 didn`t work :(

Can you help me?

**Comment by instalator** [comment]
Check in the terminal of the router

**Comment by andromedi4** [comment]
Different syntax in terminal, but it work

ip kid-control pause kid1 
ip kid-control resume  kid1

**Comment by instalator** [comment]
try this. Just update the adapter to version first 1.0.13
ip/kid-control/pause kid1
ip/kid-control/resume kid1

**Comment by instalator** [comment]
Working? Can I close the topic?

**Comment by andromedi4** [comment]
unfortunately does not work :(

**Comment by instalator** [comment]
Why does not it work? what's in the log? What's in the response object? I'm not a telepathic person.

**Comment by andromedi4** [comment]
Sorry, 
I tried this: "ip/kid-control/pause kid1"
response - "no such command"

log clear :(

I'm using latest version: 1.0.14

**Comment by instalator** [comment]
Update adapter from github and check "ip/kid-control/pause kid1"

**Comment by andromedi4** [comment]
I updated to version 1.0.15, but it doesn`t work :(

when I enter a command ("ip/kid-control/pause kid1"), now it works out, but pauses for all children 


mikrotik.0 | 2021-02-15 08:40:20.989 | info | (588) SetCommand Done response: []
-- | -- | -- | --
mikrotik.0 | 2021-02-15 08:39:26.671 | info | (588) MikroTik Connected to: 172.16.0.1
mikrotik.0 | 2021-02-15 08:39:26.622 | info | (588) starting. Version 1.0.15 in /opt/iobroker/node_modules/iobroker.mikrotik, node: v12.20.1, js-controller: 3.1.6

**Comment by instalator** [comment]
Use `ip/kid-control/print` first to get a list of all children. Enable and disable using `id` in the request.
`ip/kid-control/pause .id=*2` and `ip/kid-control/resume .id=*2`
By name, api does not support.

**Comment by andromedi4** [comment]
Thank you! Now is working! :)
