### ISSUE TITLE
Interface Wifi Datapoints

### ISSUE THREAD

**Issue by fladdie** [instalator/ioBroker.mikrotik#35]
It would be great to get the following data points for monitoring the wifi connection.

Interface: Wifi

Last Link Down
Last Link Up
Link Downs
Connected
Signal
MCS
PHY Rate
RSSI

**Comment by instalator** [comment]
Execute `interface/wireless/registration-table/print` in `mikrotik.0.commands.raw` and give me the result from the object `mikrotik.0.commands.response`.

**Comment by fladdie** [comment]
unfortunately response remains empty []
The device from which I want to retrieve the data points is a LHG 60G in bridge mode.

Today I updated the adapter and saw that you have added last link up and last link down.

**Comment by instalator** [comment]
Do you need anything else?
