### ISSUE TITLE
Add function

### ISSUE THREAD

**Issue by SpectreKr** [instalator/ioBroker.mikrotik#7]
надо в листы добавить, если есть, address-list и желательно реализовать, чтоб при изменении этого списка, адресс добавлялся в ссответствующий список в фаерволе

так можно получить списки и составляющие /ip/firewall/address-list/print
Добавление, как пример
setState('mikrotik.0.commands.raw', '/ip/firewall/address-list/add\n=list=2vpn\n=address=195.82.146.0/24\n=comment=rutracker.org');

**Comment by instalator** [comment]
Проверь версию 1.0.1

**Comment by instalator** [comment]
ready
