### ISSUE TITLE
Отваливается по таймауту, если роутер без wifi

### ISSUE THREAD

**Issue by Haba1234** [instalator/ioBroker.mikrotik#9]
![photo_2018-05-10_14-30-17](https://user-images.githubusercontent.com/24699482/39875321-fe9a07c6-5478-11e8-8fa5-f369254c74f1.jpg)
![photo_2018-05-10_14-48-41](https://user-images.githubusercontent.com/24699482/39875323-01745fd2-5479-11e8-84ea-7745eba46c12.jpg)
Вылетает по таймауту на закомментированной функции

**Comment by instalator** [comment]
Проверь версию 1.0.1

**Comment by Haba1234** [comment]
отваливаться перестало, но в объекте "lists.wifi_list" пусто
и пишет в лог: mikrotik.0 Mikrotik is not WiFi
Хотя этот микротик с wifi активным

**Comment by instalator** [comment]
Что значит перестало отваливаться?

**Comment by Haba1234** [comment]
реконект, что был в первом сообщении

**Comment by instalator** [comment]
Так у тебя маршрутизатор с вайфаем или нет? Загрузка проца какая?

**Comment by Haba1234** [comment]
у меня их 2 шт, один с вайфаем, второй без.
С вайфаем загрузка до 20% раз в 6-10 сек, средняя 6-8%

**Comment by instalator** [comment]
Нашел ошибку, установи с гита

**Comment by instalator** [comment]
переустанови
